# This is a basic workflow to help you get started with Actions

name: Pull vaccine dashboard json
# Controls when the action will run.
on:
  schedule:
    # every day at 11:30 pm UTC/4:30 PM Tuesday, in Albuquerque, NM
    - cron:  '45 23 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  acquire_html:
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks
    # executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so your job can access it
      - uses: actions/checkout@main

      # Configure Python.
      - name: Setup Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run script
        run: |
          # pipenv run python acquire-json.py
          # pipenv run python compile-daily-county-csv.py
          # pipenv run python build-latest-county-csv.py
          # pipenv run python build-latest-county-json.py
          # pipenv run python update-latest-county-csv.py

      # If any new data was fetched, create a new commit to the repo.
      - name: Commit data to repo.
        run: |
          git config --global user.email "christopherlawrencekeller@gmail.com"
          git config --global user.name "chrislkeller"
          git add -A
          timestamp=$(date -u)
          git commit -m "Updates with the latest county-level json data: ${timestamp}" || exit 0
          git push
