# This is a basic workflow to help you get started with Actions

name: Pull vaccine dashboard html
# Controls when the action will run.
on:
  schedule:
    # - cron:  '0 17 * * *' # every day at 5pm
    - cron:  '*/15 * * * *' # every 15 minutes

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    collect-data-job:
      name: Fetch New Tweets
      runs-on: ubuntu-18.04

      # Steps represent a sequence of tasks
      # executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE
        # so your job can access it
        - uses: actions/checkout@main

        # Configure Python.
        - name: Setup Python 3.7.
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        - name: Pipenv for Github Actions
          # You may pin to the exact commit or the version.
          uses: VaultVulp/action-pipenv@v2.0.1
          with:
            # pipenv command and its argument to be executed
            command:
              pipenv install
              pipenv run python acquire-html.py

        # If any new data was fetched, create a new commit to the repo.
        - name: Commit data to repo.
          run: |
            git config --global user.email "christopherlawrencekeller@gmail.com"
            git config --global user.name "chrislkeller"
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
