# This is a basic workflow to help you get started with Actions

name: Pull vaccine dashboard html
# Controls when the action will run. 
on:
  schedule:
    - cron:  '0 18 * * *' # every day at 5pm

# on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  collect-data-job:
    name: Fetch New Tweets
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Configure Python. 
      - name: Setup Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.8
